### ISSUE TITLE
FlunetdClientの持ち方に対しての考察（weakreference cache & singleton pattern）

### ISSUE THREAD

**Issue by h-oh** [oz-sysb/fluent-logger#1]
WIP

時間あったらＰＲ上げてみる。

Loggerはいろんなところで呼ばれる場合が多い。スコープやファイルが違う場合は、そのたびにNewをするが、そのたびにtd-agentのconnection resourceが生成されるとか、同じ属性をもつLoggerが、重複に存在し、以前のLoggerはreferenceを失いことによるMemory Leakなどを

weakreference cache Patternや、singleton Patternで、改善できるのではないかなと。

ただ、完全にsingletonにしてしまうと、一つのロガー属性した使えず、柔軟性を完全に失うことでまた、使えない問題に出る可能性と、属性整合性が崩れるとかもあるので、
1application内では、属性が変わらないと思われる FluentdClientはstaticで、ロガーはNew または Cache & Getterとかでいいと考えている。

ただまた、fluentd libraryでそれを最適化していて、いくらnewしても関係のない処理になっているなら、別に直さなくてもいい気がする。

https://github.com/oz-sysb/fluent-logger/blob/98cb6fb09902ca4f45a5f51401b9da97844983f8/src/OzLogger.php#L136

**Comment by ozv-s-urabe** [comment]
> weakreference cache Patternや、singleton Pattern

このあたり実装するのがよさそうですね。

**Comment by h-oh** [comment]
こういうふうに書きましたが、

- aslan-batchのように、別途Utility Classで指定して使う想定なら、やる必要性は薄くなる？
- weak referenceは、php 7.4からサポートするので、現状のシステムのphp versionを考えると、やるなら singleton(cacheはoption)になるが、上記の理由があれば、やる必要性は薄くなる。

のですね。
